### ISSUE TITLE
Where can I find FLAC.framework

### ISSUE THREAD

**Issue by arthurj58** [ap4y/OrigamiEngine#3]
OrigamiEngine-master/OrigamiEngine/Plugins/FlacDecoder.m:24:9: 'FLAC/all.h' file not found

Thank you very much

**Comment by diogobalseiro** [comment]
The default podspec includes the flac framework by default? I'm noticing my project is not including anywhere..

Using 'pod 'OrigamiEngine', '~> 1.0.14''

**Comment by ap4y** [comment]
No by default only `Core` is included.
