### ISSUE TITLE
Missing FlacDecoder and OpusFileDecoder after pod install

### ISSUE THREAD

**Issue by qubblr** [ap4y/OrigamiEngine#51]
![screen shot 2015-02-08 at 18 59 05](https://cloud.githubusercontent.com/assets/1073573/6096762/c92f4468-afc4-11e4-968e-3e5abb42b7d6.png)

**Comment by ap4y** [comment]
`flac` and `opus` integration were extracted into subspecs, you can include those with `OrigamiEngine/Flac` and `OrigamiEngine/Opus`

**Comment by qubblr** [comment]
Thank you very much
